version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=movielog
      - POSTGRES_USER=movielog
      - POSTGRES_PASSWORD=movielog
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    healthcheck:
      test: 'pg_isready -h localhost -p 5432 -q -U movielog'
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 40s

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: movie-log-be:0.1.0
    container_name: movie-log-be
    ports:
      - '4000:4000'
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./src:/usr/app/src
    env_file: ./.env
