version: '3.7'

services:
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=movielog
      - POSTGRES_USER=movielog
      - POSTGRES_PASSWORD=movielog
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - '5432:5432'
    healthcheck:
      test: 'pg_isready -h localhost -p 5432 -q -U movielog'
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 40s

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: movie-log-api:0.1.0
    container_name: movie-log-api
    ports:
      - '4000:4000'
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./src:/usr/app/src
    environment:
      - DB_ENDPOINT=db
      - DB_USERNAME=movielog
      - DB_PASSWORD=movielog
