version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=movielog
      - POSTGRES_USER=movielog
      - POSTGRES_PASSWORD=movielog
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U movielog"
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 40s
